joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0 


teleop_node:
  ros__parameters:
    enable_button: 4
    enable_turbo_button: 5
    require_enable_button: true
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
      z: 0.0
      z: 0.0
    scale_linear_turbo:
      x: 1.0
      y: 0.0
      z: 0.0
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 0.75





      